drn_perception:
  dock_detector:
    dock_detector_service_node:
      ros__parameters:
        angle_offset: 0.5
        buffer_max_size: 10
        cluster_distance: 0.35
        cluster_distance_threshold: 0.035
        cluster_size:
        - 0.15
        - 0.15
        cluster_size_threshold:
        - 0.015
        - 0.03
        eps: 0.1
        filter_radius: 0.275
        filter_z_offset: 0.06
        max_interations: 10
        max_interations_3d: 2
        min_reflectivity: 250
        min_samples: 9
        position_offset: 0.02
        reference: '[[0, -0.25], [0, -0.10], [0.10, 0], [0, 0.10], [0, 0.25]]'
        reference_3d_height: 0.15
        reference_3d_step: 0.01
        similarity_threshold: 5.0
        voxel_size: 0.02
        z_max: 0.5
        z_min: -0.5
